# Generated by Django 3.0 on 2021-05-23 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_job'),
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalstaff',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.Job'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.Job'),
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
