# Generated by Django 3.0 on 2021-05-08 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_auto_20210508_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinic',
            old_name='medical_type',
            new_name='clinic_type',
        ),
    ]
