# Generated by Django 3.0 on 2021-05-24 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_title'),
        ('clinic', '0002_auto_20210523_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.Title'),
        ),
    ]
