# Generated by Django 3.0 on 2021-05-08 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_auto_20210508_2018'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MedicalType',
            new_name='ClinicType',
        ),
    ]
