# Generated by Django 3.0 on 2021-05-09 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_auto_20210509_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='clinic',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='clinic.Clinic'),
            preserve_default=False,
        ),
    ]
