# Generated by Django 3.0 on 2021-05-09 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_staffprofile_clinic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Bilinmiyor')], max_length=2)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.Clinic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='job',
        ),
        migrations.DeleteModel(
            name='StaffProfile',
        ),
        migrations.AddField(
            model_name='staff',
            name='specialisations',
            field=models.ManyToManyField(to='clinic.Specialization'),
        ),
    ]
