# Generated by Django 3.0 on 2021-05-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_language'),
        ('clinic', '0009_auto_20210509_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='languages',
            field=models.ManyToManyField(to='administration.Language'),
        ),
    ]
