# Generated by Django 3.0 on 2021-05-09 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0012_auto_20210509_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.Job'),
        ),
    ]
