# Generated by Django 3.0 on 2021-05-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0013_staff_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
