# Generated by Django 3.0 on 2021-05-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0014_auto_20210509_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='photo',
            field=models.ImageField(default=0, upload_to='profile'),
            preserve_default=False,
        ),
    ]
